### ISSUE TITLE
Appending img to card Div

### ISSUE THREAD

**Issue by prwelber** [prwelber/prwelber.github.io#3]
Hi Anna,
Having trouble getting the card images to stick to the corresponding divs. I've tried to insert them through the below method, as well as setting CSS attr through jquery and making them the background image. This has been driving me crazy since last night. Any advice? I also moved all the images out of a sub-directory and into the same one as the .js, .html, and .css files. Each card is an object which holds the image file name. So in the below, i'm trying to the set the image source to the path found in the card that is in index position zero in the dealer's hand, which is an array.

```
$("<img src='dealerHand[0].name'>").appendTo($("#d1"));
```

**Comment by annarankin** [comment]
Hey Phil, we're in a planning meeting at the moment - meet in an hour?

**Comment by prwelber** [comment]
Sounds good. I'll be on the 2nd floor, where I was yesterday afternoon. Thanks!
