### ISSUE TITLE
Hello Again

### ISSUE THREAD

**Issue by prwelber** [prwelber/prwelber.github.io#4]
Hi,
So i'm trying to use this function to replace all the instances where I'm getting the total for the player. This isn't working, whereas before I didn't use a function and had lines 2-5 every time I needed that calculation. I have 2nd issue but I believe that's purely a scope thing. It's another instance where I'm trying to clean things up and it's breaking. 

```
/////function for getting player total
 var getPlayerTotal = function getPlayerTotal(){
 	var playerTotal = 0;
	playerHand.map(function(value, index, array){
	playerTotal += value.value;
	return playerTotal;
 	})
}
```

**Comment by annarankin** [comment]
Hey Phil! The only thing that strikes me as odd about this is `value.value` - how are you setting up your data?

**Comment by prwelber** [comment]
Each card is an object that has 3 properties, name (1,2,jack, queen, etc..) suit(hearts, spades, etc..) and value(jack would be 10, ace would be 11, 5 is 5, etc..)

I understand it as map throws out 3 arguments (don't know what to call them exactly) and so I'm looking to get the value out of the value obj property.

**Comment by annarankin** [comment]
Hey Phil, I'm coming down to talk to Calvin soon - I'll come find you once we're done and we can look over the code!

**Comment by prwelber** [comment]
OK, thanks so much!
